const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Setup-Key','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const id=p=>p+'_'+crypto.randomUUID().replaceAll('-',''); const now=()=>new Date().toISOString();
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hash(p,s){return sha(s+':'+p)} const body=r=>r.json().catch(()=>({}));
const token=r=>(r.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');
async function me(env,r){const t=token(r);if(!t)return null;return env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').bind(t,now()).first()}
function safe(u){if(!u)return null;const{password_hash,...x}=u;return x}
async function user(env,r){const u=await me(env,r);if(!u)throw Error('UNAUTHORIZED');await env.DB.prepare('UPDATE users SET last_seen=?,online=1 WHERE id=?').bind(now(),u.id).run();return u}
async function admin(env,r){const u=await user(env,r);if(!u.is_admin)throw Error('FORBIDDEN');return u}
const sellerActive=u=>u&&u.seller_until&&new Date(u.seller_until)>new Date()&&u.seller_status==='ACTIVE';
async function setting(env,key,fallback=''){const x=await env.DB.prepare('SELECT value FROM app_settings WHERE key=?').bind(key).first();return x?.value??fallback}
async function conv(env,members,type='DIRECT',orderId=null){
  if(type==='DIRECT'&&members.length===2){const x=await env.DB.prepare(`SELECT c.id FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id JOIN conversation_members b ON b.conversation_id=c.id WHERE c.type='DIRECT' AND a.user_id=? AND b.user_id=? LIMIT 1`).bind(members[0],members[1]).first();if(x)return x.id}
  if(orderId){const x=await env.DB.prepare('SELECT id FROM conversations WHERE order_id=? LIMIT 1').bind(orderId).first();if(x)return x.id}
  const cid=id('chat');await env.DB.prepare('INSERT INTO conversations(id,type,order_id) VALUES(?,?,?)').bind(cid,type,orderId).run();
  for(const m of [...new Set(members)])await env.DB.prepare('INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?)').bind(cid,m).run();return cid;
}
async function msg(env,cid,sender,text){await env.DB.prepare('INSERT INTO messages(id,conversation_id,sender_id,body) VALUES(?,?,?,?)').bind(id('msg'),cid,sender,text).run()}
async function ensureAdmin(env){return env.DB.prepare('SELECT id FROM users WHERE is_admin=1 LIMIT 1').first()}

async function register(env,b){
 const name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase()||null,phone=String(b.phone||'').trim()||null,p=String(b.password||'');
 if(!name||!p||(!email&&!phone))throw Error('Nama, email atau nomor, dan password wajib diisi');if(p.length<6)throw Error('Password minimal 6 karakter');
 if(email&&await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())throw Error('Email sudah dipakai');if(phone&&await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first())throw Error('Nomor sudah dipakai');
 const salt=id('salt'),ph=await hash(p,salt),uid=id('usr');await env.DB.prepare('INSERT INTO users(id,email,phone,name,password_hash,last_seen,online) VALUES(?,?,?,?,?,?,1)').bind(uid,email,phone,name,salt+'$'+ph,now()).run();return login(env,{identifier:email||phone,password:p});
}
async function login(env,b){const ident=String(b.identifier||'').trim().toLowerCase(),p=String(b.password||'');const u=await env.DB.prepare('SELECT * FROM users WHERE lower(email)=? OR phone=?').bind(ident,ident).first();if(!u)throw Error('Nomor/email atau password salah');const [salt,stored]=String(u.password_hash).split('$');if(await hash(p,salt)!==stored)throw Error('Nomor/email atau password salah');const t=crypto.randomUUID()+crypto.randomUUID(),exp=new Date(Date.now()+30*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(t,u.id,exp).run();await env.DB.prepare('UPDATE users SET last_seen=?,online=1 WHERE id=?').bind(now(),u.id).run();return{token:t,user:safe(u)} }

async function api(env,r){const u0=new URL(r.url),p=u0.pathname.replace(/^\/api/,'')||'/';if(r.method==='OPTIONS')return new Response('',{headers:CORS});
 if(r.method==='GET'&&p==='/health')return json({ok:true,service:'Velora Backend',version:'14.0'});
 if(r.method==='POST'&&p==='/auth/register')return json(await register(env,await body(r)));
 if(r.method==='POST'&&p==='/auth/login')return json(await login(env,await body(r)));
 if(r.method==='POST'&&p==='/auth/logout'){const t=token(r);if(t){const x=await me(env,r);if(x)await env.DB.prepare('UPDATE users SET online=0,last_seen=? WHERE id=?').bind(now(),x.id).run();await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(t).run()}return json({ok:true})}
 if(r.method==='POST'&&p==='/setup/admin'){
   const key=r.headers.get('X-Setup-Key');if(!env.SETUP_KEY||key!==env.SETUP_KEY)throw Error('FORBIDDEN');
   if(await ensureAdmin(env))throw Error('Admin sudah ada');const b=await body(r);const name=b.name||'Velora Admin',email=String(b.email||'').toLowerCase(),phone=b.phone||null,pass=b.password||'';if(!email||!pass)throw Error('Email dan password admin wajib');const salt=id('salt'),ph=await hash(pass,salt),uid=id('adm');await env.DB.prepare('INSERT INTO users(id,email,phone,name,password_hash,is_admin,last_seen,online) VALUES(?,?,?,?,?,?,?,0)').bind(uid,email,phone,name,salt+'$'+ph,1,now()).run();return json({ok:true,id:uid});
 }
 const u=await user(env,r);
 if(r.method==='GET'&&p==='/me')return json({user:safe(u)});
 if(r.method==='GET'&&p==='/config')return json({sellerPrice:Number(await setting(env,'seller_price',env.SELLER_PRICE||15000)),sellerDays:Number(await setting(env,'seller_days',env.SELLER_DAYS||15)),adminFee:Number(await setting(env,'admin_fee',env.ADMIN_FEE||3000)),qris:await setting(env,'qris_text','Fadli Store, Cell | NMID ID1026609564020 | A01'),qrisImage:await setting(env,'qris_image','https://files.catbox.moe/xjce6d.jpg')});
 if(r.method==='PUT'&&p==='/profile'){const b=await body(r);await env.DB.prepare('UPDATE users SET name=?,phone=? WHERE id=?').bind(String(b.name||u.name).trim(),String(b.phone||u.phone||'').trim()||null,u.id).run();return json({ok:true})}
 if(r.method==='GET'&&p==='/products'){const rows=await env.DB.prepare(`SELECT p.*,u.name seller_name,u.seller_until,u.seller_status FROM products p JOIN users u ON u.id=p.seller_id WHERE p.status='APPROVED' ORDER BY p.created_at DESC`).all();return json({products:rows.results||[]})}
 if(r.method==='GET'&&p==='/seller/status')return json({active:sellerActive(u),until:u.seller_until,status:u.seller_status,balance:u.balance||0});
 if(r.method==='POST'&&p==='/seller/pay'){const b=await body(r),price=Number(await setting(env,'seller_price',15000)),days=Number(await setting(env,'seller_days',15));if(sellerActive(u))throw Error('Seller masih aktif');const pending=await env.DB.prepare("SELECT id FROM seller_payments WHERE user_id=? AND status='PENDING'").bind(u.id).first();if(pending)throw Error('Pembayaran seller masih menunggu verifikasi');const pid=id('sp');await env.DB.prepare('INSERT INTO seller_payments(id,user_id,amount,days,method,proof) VALUES(?,?,?,?,?,?)').bind(pid,u.id,price,days,b.method||'QRIS',b.proof||'').run();return json({ok:true,id:pid,status:'PENDING'})}
 if(r.method==='GET'&&p==='/seller/listings'){const rows=await env.DB.prepare('SELECT * FROM products WHERE seller_id=? ORDER BY created_at DESC').bind(u.id).all();return json({products:rows.results||[]})}
 if(r.method==='POST'&&p==='/seller/listings'){if(!u.is_admin&&!sellerActive(u))throw Error('Seller belum aktif');const b=await body(r);if(!b.title||!b.game||!Number(b.price))throw Error('Judul, game, dan harga wajib');const pid=id('prd');await env.DB.prepare("INSERT INTO products(id,seller_id,game,title,price,description,photos,status) VALUES(?,?,?,?,?,?,?,?)").bind(pid,u.id,b.game,b.title,Number(b.price),b.description||'',JSON.stringify(b.photos||[]),'APPROVED').run();return json({ok:true,id:pid,status:'APPROVED'})}
 if(r.method==='GET'&&p==='/orders'){const rows=await env.DB.prepare(`SELECT o.*,p.title,p.game,ub.name buyer_name,us.name seller_name FROM orders o JOIN products p ON p.id=o.product_id JOIN users ub ON ub.id=o.buyer_id JOIN users us ON us.id=o.seller_id WHERE o.buyer_id=? OR o.seller_id=? ORDER BY o.created_at DESC`).bind(u.id,u.id).all();return json({orders:rows.results||[]})}
 if(r.method==='POST'&&p==='/orders'){const b=await body(r),prod=await env.DB.prepare("SELECT * FROM products WHERE id=? AND status='APPROVED'").bind(b.productId).first();if(!prod)throw Error('Akun tidak ditemukan');if(prod.seller_id===u.id)throw Error('Tidak bisa membeli akun sendiri');const fee=Number(await setting(env,'admin_fee',3000)),oid=id('ord');await env.DB.prepare('INSERT INTO orders(id,buyer_id,seller_id,product_id,price,admin_fee,total,payment_method) VALUES(?,?,?,?,?,?,?,?)').bind(oid,u.id,prod.seller_id,prod.id,prod.price,fee,prod.price+fee,b.method||'QRIS').run();const cid=await conv(env,[u.id,prod.seller_id],'DIRECT');await msg(env,cid,u.id,`Pesanan ${oid} dibuat.\nAkun: ${prod.title}\nHarga: Rp${Number(prod.price).toLocaleString('id-ID')}\nBiaya admin: Rp${fee.toLocaleString('id-ID')}\nTotal: Rp${(prod.price+fee).toLocaleString('id-ID')}`);return json({ok:true,orderId:oid,total:prod.price+fee})}
 if(r.method==='POST'&&p.match(/^\/orders\/[^/]+\/paid$/)){const oid=p.split('/')[2],b=await body(r),o=await env.DB.prepare('SELECT o.*,p.title FROM orders o JOIN products p ON p.id=o.product_id WHERE o.id=? AND o.buyer_id=?').bind(oid,u.id).first();if(!o)throw Error('Pesanan tidak ditemukan');if(o.status!=='WAITING_PAYMENT')throw Error('Pesanan sudah dikirim ke proses verifikasi');await env.DB.prepare("UPDATE orders SET status='VERIFYING',payment_method=?,payment_proof=?,paid_at=? WHERE id=?").bind(b.method||o.payment_method,b.proof||'',now(),oid).run();const admins=await env.DB.prepare('SELECT id FROM users WHERE is_admin=1').all();for(const a of admins.results||[]){const c=await conv(env,[u.id,a.id],'DIRECT');await msg(env,c,u.id,`Transaksi: ${oid}\nAkun: ${o.title}\nSeller: ${o.seller_id}\nBuyer: ${u.name}\nHarga akun: Rp${Number(o.price).toLocaleString('id-ID')}\nBiaya admin: Rp${Number(o.admin_fee).toLocaleString('id-ID')}\nTotal Pembayaran: Rp${Number(o.total).toLocaleString('id-ID')}\nPembayaran menggunakan: ${b.method||o.payment_method}\nStatus: MENUNGGU VERIFIKASI ADMIN`)}return json({ok:true,status:'VERIFYING'})}
 if(r.method==='POST'&&p.match(/^\/orders\/[^/]+\/complete$/)){const oid=p.split('/')[2];const o=await env.DB.prepare('SELECT * FROM orders WHERE id=? AND buyer_id=?').bind(oid,u.id).first();if(!o)throw Error('Pesanan tidak ditemukan');if(o.status!=='DELIVERED')throw Error('Pesanan belum ditandai dikirim seller');await env.DB.prepare("UPDATE orders SET status='COMPLETED',completed_at=? WHERE id=?").bind(now(),oid).run();await env.DB.prepare('UPDATE users SET balance=balance+? WHERE id=?').bind(o.price,o.seller_id).run();await env.DB.prepare("UPDATE products SET status='SOLD' WHERE id=?").bind(o.product_id).run();const c=await conv(env,[u.id,o.seller_id],'DIRECT');await msg(env,c,u.id,'Pembeli mengonfirmasi pesanan selesai. Saldo seller diproses.');return json({ok:true})}
 if(r.method==='GET'&&p==='/chats'){const rows=await env.DB.prepare(`SELECT c.id,c.type,c.order_id,MAX(m.created_at) last_time,(SELECT body FROM messages z WHERE z.conversation_id=c.id ORDER BY z.created_at DESC LIMIT 1) last_body,(SELECT COUNT(*) FROM messages z WHERE z.conversation_id=c.id AND z.sender_id<>? AND z.read_at IS NULL) unread FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id LEFT JOIN messages m ON m.conversation_id=c.id WHERE cm.user_id=? GROUP BY c.id ORDER BY last_time DESC`).bind(u.id,u.id).all();return json({chats:rows.results||[]})}
 if(r.method==='GET'&&p.startsWith('/chats/')){const cid=p.split('/')[2],ok=await env.DB.prepare('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?').bind(cid,u.id).first();if(!ok)throw Error('FORBIDDEN');const rows=await env.DB.prepare(`SELECT m.*,u.name,u.is_admin,u.seller_status FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.conversation_id=? ORDER BY m.created_at ASC LIMIT 500`).bind(cid).all();await env.DB.prepare('UPDATE messages SET read_at=? WHERE conversation_id=? AND sender_id<>? AND read_at IS NULL').bind(now(),cid,u.id).run();return json({messages:rows.results||[]})}
 if(r.method==='POST'&&p.match(/^\/chats\/[^/]+\/messages$/)){const cid=p.split('/')[2],b=await body(r),ok=await env.DB.prepare('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?').bind(cid,u.id).first();if(!ok)throw Error('FORBIDDEN');if(!String(b.body||'').trim())throw Error('Pesan kosong');await msg(env,cid,u.id,String(b.body).trim());return json({ok:true})}
 if(r.method==='POST'&&p==='/chats/admin'){const a=await ensureAdmin(env);if(!a)throw Error('Admin belum dibuat');const cid=await conv(env,[u.id,a.id],'DIRECT');return json({id:cid})}
 if(r.method==='POST'&&p==='/withdrawals'){if(!sellerActive(u))throw Error('Seller tidak aktif');const b=await body(r),amount=Number(b.amount);if(!amount||amount<=0||amount>Number(u.balance||0))throw Error('Saldo tidak cukup');const wid=id('wd');await env.DB.prepare('UPDATE users SET balance=balance-? WHERE id=?').bind(amount,u.id).run();await env.DB.prepare('INSERT INTO withdrawals(id,seller_id,amount,method,destination) VALUES(?,?,?,?,?)').bind(wid,u.id,amount,b.method||'Bank',b.destination||'').run();return json({ok:true,id:wid})}
 if(r.method==='POST'&&p==='/admin/listings'&&u.is_admin){const b=await body(r);if(!b.title||!b.game||!Number(b.price))throw Error('Judul, game, dan harga wajib');const pid=id('prd');await env.DB.prepare("INSERT INTO products(id,seller_id,game,title,price,description,photos,status) VALUES(?,?,?,?,?,?,?,?)").bind(pid,u.id,b.game,b.title,Number(b.price),b.description||'',JSON.stringify(b.photos||[]),'APPROVED').run();return json({ok:true,id:pid,status:'APPROVED'})}
 if(u.is_admin){
  if(r.method==='GET'&&p==='/admin/stats'){const [users,products,orders,pending,reports]=await Promise.all([env.DB.prepare('SELECT COUNT(*) n FROM users').first(),env.DB.prepare("SELECT COUNT(*) n FROM products WHERE status='APPROVED'").first(),env.DB.prepare('SELECT COUNT(*) n FROM orders').first(),env.DB.prepare("SELECT COUNT(*) n FROM seller_payments WHERE status='PENDING'").first(),env.DB.prepare("SELECT COUNT(*) n FROM reports WHERE status='OPEN'").first()]);return json({users:users.n,products:products.n,orders:orders.n,pendingSeller:pending.n,openReports:reports.n})}
  if(r.method==='GET'&&p==='/admin/users'){const rows=await env.DB.prepare('SELECT id,name,email,phone,is_admin,seller_until,seller_status,balance,created_at,last_seen,online FROM users ORDER BY created_at DESC').all();return json({users:rows.results||[]})}
  if(r.method==='GET'&&p==='/admin/seller-payments'){const rows=await env.DB.prepare('SELECT sp.*,u.name,u.email,u.phone FROM seller_payments sp JOIN users u ON u.id=sp.user_id ORDER BY sp.created_at DESC').all();return json({payments:rows.results||[]})}
  if(r.method==='POST'&&p.match(/^\/admin\/seller-payments\/[^/]+\/decision$/)){const pid=p.split('/')[3],b=await body(r),pay=await env.DB.prepare('SELECT * FROM seller_payments WHERE id=?').bind(pid).first();if(!pay)throw Error('Pembayaran tidak ditemukan');if(pay.status!=='PENDING')throw Error('Sudah diproses');if(b.ok){const days=pay.days||15,base=(await env.DB.prepare('SELECT seller_until FROM users WHERE id=?').bind(pay.user_id).first()).seller_until;const start=base&&new Date(base)>new Date()?new Date(base):new Date();start.setDate(start.getDate()+days);await env.DB.prepare("UPDATE seller_payments SET status='PAID',reviewed_at=? WHERE id=?").bind(now(),pid).run();await env.DB.prepare("UPDATE users SET seller_until=?,seller_status='ACTIVE' WHERE id=?").bind(start.toISOString(),pay.user_id).run();}else await env.DB.prepare("UPDATE seller_payments SET status='FAILED',reviewed_at=? WHERE id=?").bind(now(),pid).run();return json({ok:true})}
  if(r.method==='GET'&&p==='/admin/products'){const rows=await env.DB.prepare('SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id ORDER BY p.created_at DESC').all();return json({products:rows.results||[]})}
  if(r.method==='POST'&&p.match(/^\/admin\/products\/[^/]+\/decision$/)){const pid=p.split('/')[3],b=await body(r);await env.DB.prepare('UPDATE products SET status=? WHERE id=?').bind(b.ok?'APPROVED':'REJECTED',pid).run();return json({ok:true})}
  if(r.method==='GET'&&p==='/admin/orders'){const rows=await env.DB.prepare(`SELECT o.*,p.title,ub.name buyer_name,us.name seller_name FROM orders o JOIN products p ON p.id=o.product_id JOIN users ub ON ub.id=o.buyer_id JOIN users us ON us.id=o.seller_id ORDER BY o.created_at DESC`).all();return json({orders:rows.results||[]})}
  if(r.method==='POST'&&p.match(/^\/admin\/orders\/[^/]+\/decision$/)){const oid=p.split('/')[3],b=await body(r),o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(oid).first();if(!o)throw Error('Pesanan tidak ditemukan');const status=b.action==='ACCEPT_PAYMENT'?'PAID':b.action==='REJECT_PAYMENT'?'PAYMENT_FAILED':b.action==='MARK_DELIVERED'?'DELIVERED':o.status;await env.DB.prepare('UPDATE orders SET status=? WHERE id=?').bind(status,oid).run();const c=await conv(env,[o.buyer_id,o.seller_id],'DIRECT');await msg(env,c,u.id,`Admin memperbarui transaksi ${oid}: ${status}`);return json({ok:true,status})}
  if(r.method==='GET'&&p==='/admin/withdrawals'){const rows=await env.DB.prepare('SELECT w.*,u.name,u.phone,u.email FROM withdrawals w JOIN users u ON u.id=w.seller_id ORDER BY w.created_at DESC').all();return json({withdrawals:rows.results||[]})}
  if(r.method==='POST'&&p.match(/^\/admin\/withdrawals\/[^/]+\/decision$/)){const wid=p.split('/')[3],b=await body(r),w=await env.DB.prepare('SELECT * FROM withdrawals WHERE id=?').bind(wid).first();if(!w)throw Error('Penarikan tidak ditemukan');if(w.status!=='PENDING')throw Error('Sudah diproses');if(b.ok)await env.DB.prepare("UPDATE withdrawals SET status='PAID',reviewed_at=? WHERE id=?").bind(now(),wid).run();else{await env.DB.prepare("UPDATE withdrawals SET status='FAILED',reviewed_at=? WHERE id=?").bind(now(),wid).run();await env.DB.prepare('UPDATE users SET balance=balance+? WHERE id=?').bind(w.amount,w.seller_id).run()}return json({ok:true})}
  if(r.method==='GET'&&p==='/admin/reports'){const rows=await env.DB.prepare('SELECT r.*,u.name reporter FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.created_at DESC').all();return json({reports:rows.results||[]})}
  if(r.method==='POST'&&p.match(/^\/admin\/reports\/[^/]+\/resolve$/)){const rid=p.split('/')[3];await env.DB.prepare("UPDATE reports SET status='RESOLVED',resolved_at=? WHERE id=?").bind(now(),rid).run();return json({ok:true})}
  if(r.method==='PUT'&&p==='/admin/settings'){const b=await body(r);for(const k of ['qris_text','admin_fee','seller_price','seller_days'])if(b[k]!==undefined)await env.DB.prepare('INSERT OR REPLACE INTO app_settings(key,value) VALUES(?,?)').bind(k,String(b[k])).run();return json({ok:true})}
 }
 throw Error('NOT_FOUND');
}
export default {async fetch(r,env){try{return await api(env,r)}catch(e){const m=e.message||'Server error';return json({error:m},m==='UNAUTHORIZED'?401:m==='FORBIDDEN'?403:m==='NOT_FOUND'?404:400)}}};
